[package]
name = "shiba-preview"
version = "0.0.0"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
description = "Simple markdown previewer"
edition = "2021"
license = "MIT"
repository = "https://github.com/rhysd/Shiba"
include = ["src", "README.md"]

[[bin]]
name = "shiba"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.0.2"
ammonia = "3.3.0"
anyhow = "1.0.72"
dirs = "5.0.1"
emojis = "0.6.0"
env_logger = "0.10.0"
getopts = "0.2.21"
log = "0.4.19"
memchr = "2.5.0"
notify = "6.0.1"
once_cell = "1.18.0"
open = "5.0.0"
phf = { version = "0.11.2", features = ["macros"] }
# https://github.com/raphlinus/pulldown-cmark/pull/622
pulldown-cmark = { git = "https://github.com/rhysd/pulldown-cmark.git", branch="math-0.9.3", default-features = false, features = [] }
regex = "1.9.3"
rfd = "0.11.4"
serde = "1.0.183"
serde_json = "1.0.104"
serde_yaml = "0.9.25"
wry = "0.30.0"

[features]
default = []
__bench = []
devtools = ["wry/devtools"]

[workspace]
members = ["bench"]

[profile.bench]
lto = "thin"

[dev-dependencies]
insta = { version = "1.31.0", features = ["json"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[package.metadata.bundle]
name = "Shiba"
identifier = "io.github.rhysd.shiba"
icon = [
    "assets/icon.ico",
    "assets/icon.icns",
    "assets/icon.iconset/icon_32x32.png",
    "assets/icon.iconset/icon_64x64.png",
    "assets/icon.iconset/icon_128x128.png",
    "assets/icon.iconset/icon_256x256.png",
    "assets/icon.iconset/icon_256x256@2x.png",
]
copyright = "Copyright (c) 2015 rhysd"
category = "public.app-category.productivity"
deb_depends = ["libwebkit2gtk-4.1-dev"]
osx_url_schemes = ["shiba"]
