[package]
name = "shiba-preview"
version = "0.0.0"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
description = "Simple markdown previewer"
edition = "2021"
license = "MIT"
repository = "https://github.com/rhysd/Shiba"
include = ["src", "README.md"]

[[bin]]
name = "shiba"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.20"
ammonia = "3.3.0"
anyhow = "1.0.68"
dirs = "4.0.0"
emojis = "0.5.2"
env_logger = "0.10.0"
getopts = "0.2.21"
log = "0.4.17"
memchr = "2.5.0"
notify = "5.0.0"
once_cell = "1.17.0"
open = "3.2.0"
phf = { version = "0.11.1", features = ["macros"] }
# https://github.com/raphlinus/pulldown-cmark/pull/622
pulldown-cmark = { git = "https://github.com/rhysd/pulldown-cmark.git", branch="math", default-features = false, features = [] }
regex = "1.7.1"
rfd = "0.10.0"
serde = "1.0.152"
serde_json = "1.0.91"
serde_yaml = "0.9.16"
wry = "0.23.4"

[features]
default = []
__bench = []
devtools = ["wry/devtools"]

[workspace]
members = ["bench"]

[profile.bench]
lto = "thin"

[dev-dependencies]
insta = { version = "1.26.0", features = ["json"] }
